from get_llm import LLM
from models import Models
from sandbox import Sandbox, SandboxSample, McpServerConfig
import sys
from io import StringIO
import signal
from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional
from tqdm.rich import tqdm  # type: ignore [import-untyped]


class StepMetrics(BaseModel):
    """Metrics for a single agent step.
    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required for evaluation, empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(
        ...,
        description="Tokens sent to the LLM for thisstep")
    output_tokens: int = Field(
        ...,
        description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(
        ...,
        description="Wall-clock time for the LLM API call in milliseconds")
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when this step was recorded")
    api_url: str = Field(
        default="",
        description="Base URL of the LLM API endpoint (e.g., '"
        "https://openrouter.ai/api/v1')")
    model_name: str = Field(
        default="",
        description="Model identifier used for this step (e.g., "
        "'qwen/qwen3-235b-a22b-2507')")
    llm_output: str = Field(
        default="",
        description="Raw text generated by the LLM before code extraction")
    sandbox_input: str = Field(
        default="",
        description="Python code sent to the sandbox for execution")
    sandbox_output: str = Field(
        default="",
        description="Sandbox execution result (stdout/stderr/error message)")
    retries: int = Field(
        default=0,
        description="Number of LLM API retries before getting a successful "
        "response (0 = first attempt succeeded)")


class SolutionOutput(BaseModel):
    """Output from student solution, required format for evaluation.
    This is the JSON structure your agent must produce and write to solution.
    json.
    The moulinette validates this against task correctness and metrics limits.
    """
    task_id: str = Field(
        ...,
        description="Task identifier (MBPP task_id as string, or SWE-bench "
        "instance_id)")
    benchmark: str = Field(
        ...,
        description="Benchmark type: 'mbpp' or ' swebench'")
    success: bool = Field(
        ...,
        description="Whether the agent believes it solved the task")
    solution: str = Field(
        ...,
        description="For MBPP: the Python function code. For SWE-bench: the "
        "git patch (diff)")
    iterations: int = Field(
        ...,
        description="Number of agent loop iterations used")
    total_requests: int = Field(
        ...,
        description="Total number of LLM API requests made "
        "(including retries)")
    total_input_tokens: int = Field(
        ...,
        description="Sum of input_tokens across all steps")
    total_output_tokens: int = Field(
        ...,
        description="Sum of output_tokens across all steps")
    total_time_seconds: float = Field(
        ...,
        description="Wall-clock time from agent start to finish")
    steps: List[StepMetrics] = Field(
        default_factory=list,
        description="Perstep metrics, one entry per agent iteration")
    system_prompt: str = Field(
        default="",
        description="Full system prompt sent to the LLM (for provenance "
        "checking)")
    error: Optional[str] = Field(
        default=None,
        description="Error message if the agent failed (None if successful)")
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when the solution was produced")


class Orchestrator:
    def __init__(self) -> None:
        self.max_iterations = 3
        self.system_prompt = f"""
You are an autonomous AI agent specialized in solving programming tasks. Your goal is to write correct Python code that passes all test cases.

## YOUR ROLE
- You are a software engineer solving programming problems
- You have access to a sandbox environment where you can test your code
- You receive feedback from test execution and must iterate until successful

## TASK FORMAT
You will be given a programming task. The task will include:
- A description of what the function should do
- Input/output specifications
- Constraints (if any)
- Example test cases

## YOUR PROCESS
1. **ANALYZE** - Understand the problem requirements thoroughly
2. **PLAN** - Think about the algorithm and edge cases
3. **WRITE CODE** - Implement your solution
4. **TEST** - Run your code in the sandbox
5. **ITERATE** - Use feedback to fix issues and improve

## CODE OUTPUT FORMAT
When providing your solution, you MUST format your code as follows:

<code>
def function_name(params):
    # Your implementation here
    return result
</code>

## IMPORTANT RULES
1. **Always wrap your code in <code> tags** - This is how I identify your solution
2. **Write complete, executable Python code** - Include all necessary imports and definitions
3. **Test your code** - After writing code, it will be executed automatically
4. **Learn from errors** - Use the test output to fix bugs and edge cases
5. **Be efficient** - Aim for optimal time and space complexity
6. **Handle edge cases** - Consider empty inputs, bounds, special values

## CODE QUALITY GUIDELINES
- Write clean, readable Python code
- Use meaningful variable names
- Add comments for complex logic
- Follow Python best practices (PEP 8)
- Handle errors gracefully where appropriate

## ITERATION STRATEGY
- If tests fail, analyze the error message carefully
- Common issues: off-by-one errors, edge cases, type mismatches
- Fix one issue at a time
- Use the test output to guide your corrections

## RESPONSE FORMAT
After seeing the test output, you should:
1. Acknowledge whether the test passed or failed
2. Explain what needs to be fixed (if it failed)
3. Provide the corrected code in <code> tags

## EXAMPLE INTERACTION

User: "Write a function that adds two numbers"
Assistant: "Here's my solution:
<code>
def add(a, b):
    return a + b
</code>"

System: "stdout: Test passed!"

Assistant: "Great! The function works correctly."

System: "stdout: Test failed: Expected 5, got 3"

Assistant: "I see the issue - let me fix the logic:
<code>
def add(a, b):
    result = a + b
    return result
</code>"

## SANDBOX ENVIRONMENT
- You have access to Python's standard library
- Limited imports for security: math, collections, itertools, re, json, typing, functools, operator, heapq, bisect, copy, string, random, datetime, array, cmath
- Each code execution is isolated and safe
- Time limit: 30 seconds per execution
- Memory limit: 512 MB

## CRITICAL REMINDERS
- Always put your final answer in <code> tags
- Include the function definition with correct parameters
- Your code must be self-contained (no dependencies on external state)
- If your code prints debug information, it will be captured in stdout

Remember: You have up to {self.max_iterations} iterations to solve the problem. Use each iteration wisely to converge on a correct solution.

Now, let's solve the problem step by step!
User: "create a function f, which takes *args, being strings describing a card, and calculating the probability the two first card wins the hold them texas hand against the other cards, all exception / impossible case should be handled"
do not forget to use print() to test the function as much as possible, you have a python interpreter to yourself, you have to try your creation
"""
        mcp_conf = {
            "bench": 'mbpp',
            "connection": 'stdio',
            "arg": "python test"
        }
        self.sandbox = Sandbox('default', McpServerConfig(**mcp_conf))  # type: ignore [arg-type]
        self.llm = LLM(Models.GROQ.value)
        self.llm.log = True
        self.sample_sandbox = SandboxSample(self.sandbox.config)
        self._code_open_tag = "<code>"
        self._code_close_tag = "</code>"

        self.steps: list[StepMetrics] = []

        self.task_id: str = '0'  # FROM INPUT!

    def run_code(self, code: str) -> str:
        code_input: str = code + "\nEOF\nEOF\n"

        original_stdin = sys.stdin
        sys.stdin = StringIO(code_input)
        original_stdout = sys.stdout
        temp = StringIO()
        sys.stdout = temp
        try:
            self.sample_sandbox.use_sandbox()
        except (Exception, KeyboardInterrupt) as e:
            print("Error occured!", e)
        signal.alarm(0)
        sys.stdin = original_stdin
        result = temp.getvalue()
        sys.stdout = original_stdout
        return result

    def extract_code(self, text: str) -> str:
        from_ = text.split(self._code_open_tag)[-1]
        to_ = from_.split(self._code_close_tag)[0]
        return to_

    def run(self) -> SolutionOutput:
        iteration = 0
        prompt = self.system_prompt
        next_prompt: str | None = None
        for iteration in tqdm(range(self.max_iterations)):
            self.llm.interact(prompt)
            usage = self.llm.answer['usage']
            code = self.extract_code(self.llm.history[-1]['content'])
            self.sample_sandbox = SandboxSample(self.sandbox.config)
            next_prompt = self.run_code(code)
            step_metric = {
                "step": iteration + 1,
                "input_tokens": usage['prompt_tokens'],
                "output_tokens": usage['completion_tokens'],
                "request_time_ms": self.llm.request_time_ms,
                "api_url": self.llm.model.API_URL.value,   # type: ignore [attr-defined]
                "model_name": self.llm.model.MODEL.value,   # type: ignore [attr-defined]
                "llm_output": self.llm.history[-1]["content"],
                "sandbox_input": code,
                "sandbox_output": next_prompt,
                "retries": self.llm.retries
            }
            self.steps.append(StepMetrics(**step_metric))
            if not self.sample_sandbox.inrun:
                break
            prompt = "stdout:\n" + next_prompt
        if not self.sample_sandbox.inrun:
            next_prompt = None
            success = True
        else:
            success = False
        solution_output = {
            "task_id": self.task_id,
            "benchmark": self.sandbox.mcp_server.bench if self.sandbox.mcp_server else "mbpp",
            "success": success,
            "solution": self.sample_sandbox.result,
            "iterations": iteration,
            "total_requests": sum([i.retries for i in self.steps]),
            "total_input_tokens": sum([i.input_tokens for i in self.steps]),
            "total_output_tokens": sum([i.output_tokens for i in self.steps]),
            "total_time_seconds": sum([
                i.request_time_ms for i in self.steps]) * 1000,
            "steps": self.steps,
            "system_prompt": self.system_prompt,
            "error": next_prompt
        }
        return SolutionOutput(**solution_output)  # type: ignore [arg-type]


if __name__ == "__main__":
    sol = Orchestrator().run()
    result = sol.model_dump()
    import json
    with open('test.json', 'w') as f:
        json.dump(result, f, indent=4)
